name: Convert Python to Markdown Docs
on:
  push:
    branches:
      - dev
      - develop
    paths:
      - 'functions/**'
permissions:
  contents: write
jobs:
  python-to-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Convert into Markdown Docs
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^functions/.*\.py$')
          for file in $changed_files; do
              parent_folder=$(dirname $file)
              echo "Running Python code in $parent_folder"
              python ./tools/function_to_docs.py $parent_folder
          done
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Convert Python to Markdown Docs (${{ env.cache_id }})"
          git push